// Generated by `miniprogram host endpoint add`.
// Keep endpoint ownership in host config, not button code.
// BEGIN MINI_PROGRAM_ENDPOINTS_JSON
// {"brain_test":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"calculator":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"weather":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"}}
// END MINI_PROGRAM_ENDPOINTS_JSON

import 'package:mini_program_sdk/mini_program_sdk.dart';

import 'mini_program_policy_resolver.dart';
import 'mini_program_registry.dart';

Map<String, MiniProgramEndpoint> buildMiniProgramEndpoints() {
  return <String, MiniProgramEndpoint>{
    MiniPrograms.brainTest.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.brainTest.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.brainTest.appId,
      ),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(
        MiniPrograms.brainTest.appId,
      ),
      locationPolicy: locationPolicyForMiniProgram(
        MiniPrograms.brainTest.appId,
      ),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.calculator.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.calculator.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.calculator.appId,
      ),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(
        MiniPrograms.calculator.appId,
      ),
      locationPolicy: locationPolicyForMiniProgram(
        MiniPrograms.calculator.appId,
      ),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.weather.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.weather.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.weather.appId,
      ),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(
        MiniPrograms.weather.appId,
      ),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.weather.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
  };
}
