// Generated by miniprogram tooling.
// Runtime uses accepted host policy only.

import 'package:mini_program_contracts/mini_program_contracts.dart'
    show MiniProgramLocationAccuracy, MiniProgramLocationMode;
import 'package:mini_program_sdk/mini_program_sdk.dart';

MiniProgramCachePolicy cachePolicyForMiniProgram(String appId) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramCachePolicy(
        maxBytes: 262144,
        maxStateBytes: 262144,
        stateInactiveTtl: Duration(days: 90),
        allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{
          MiniProgramCacheBucket.state,
        },
      );
    case "calculator":
      return const MiniProgramCachePolicy(
        maxBytes: 1048576,
        maxStateBytes: 1048576,
        stateInactiveTtl: Duration(days: 30),
        allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{
          MiniProgramCacheBucket.state,
        },
      );
    case "notepad":
      return const MiniProgramCachePolicy(
        maxBytes: 1048576,
        maxStateBytes: 1048576,
        stateInactiveTtl: Duration(days: 365),
        allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{
          MiniProgramCacheBucket.state,
        },
      );
    case "weather":
      return const MiniProgramCachePolicy(
        maxBytes: 4325376,
        maxDataBytes: 4194304,
        dataTtl: Duration(days: 30),
        maxStateBytes: 131072,
        stateInactiveTtl: Duration(days: 90),
        allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{
          MiniProgramCacheBucket.data,
          MiniProgramCacheBucket.state,
        },
      );
    default:
      return const MiniProgramCachePolicy();
  }
}

MiniProgramLiveStatePolicy liveStatePolicyForMiniProgram(String appId) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramLiveStatePolicy(
        maxBytes: 2097152,
        maxEntries: 1000,
        maxValueBytes: 262144,
        maxDepth: 32,
      );
    case "calculator":
      return const MiniProgramLiveStatePolicy(
        maxBytes: 2097152,
        maxEntries: 1000,
        maxValueBytes: 262144,
        maxDepth: 32,
      );
    case "notepad":
      return const MiniProgramLiveStatePolicy(
        maxBytes: 2097152,
        maxEntries: 1000,
        maxValueBytes: 262144,
        maxDepth: 32,
      );
    case "weather":
      return const MiniProgramLiveStatePolicy(
        maxBytes: 2097152,
        maxEntries: 1000,
        maxValueBytes: 262144,
        maxDepth: 32,
      );
    default:
      return const MiniProgramLiveStatePolicy();
  }
}

MiniProgramPublisherApiPolicy publisherApiPolicyForMiniProgram(String appId) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "calculator":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "notepad":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "weather":
      return const MiniProgramPublisherApiPolicy(enabled: true);
    default:
      return const MiniProgramPublisherApiPolicy();
  }
}

MiniProgramLocationPolicy locationPolicyForMiniProgram(String appId) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramLocationPolicy(
        enabled: false,
        accuracy: MiniProgramLocationAccuracy.approximate,
        mode: MiniProgramLocationMode.whenInUse,
      );
    case "calculator":
      return const MiniProgramLocationPolicy(
        enabled: false,
        accuracy: MiniProgramLocationAccuracy.approximate,
        mode: MiniProgramLocationMode.whenInUse,
      );
    case "notepad":
      return const MiniProgramLocationPolicy(
        enabled: false,
        accuracy: MiniProgramLocationAccuracy.approximate,
        mode: MiniProgramLocationMode.whenInUse,
      );
    case "weather":
      return const MiniProgramLocationPolicy(
        enabled: true,
        accuracy: MiniProgramLocationAccuracy.approximate,
        mode: MiniProgramLocationMode.whenInUse,
      );
    default:
      return const MiniProgramLocationPolicy();
  }
}
