// Generated by `miniprogram host endpoint add`.
// Keep endpoint ownership in host config, not button code.
// BEGIN MINI_PROGRAM_ENDPOINTS_JSON
// {"brain_test":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"calculator":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"drive":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"flashlight":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"notepad":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"},"weather":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store"}}
// END MINI_PROGRAM_ENDPOINTS_JSON

import 'package:mini_program_sdk/mini_program_sdk.dart';

import 'mini_program_policy_resolver.dart';
import 'mini_program_registry.dart';

Map<String, MiniProgramEndpoint> buildMiniProgramEndpoints() {
  return <String, MiniProgramEndpoint>{
    MiniPrograms.brainTest.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.brainTest.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.brainTest.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.brainTest.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.brainTest.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.brainTest.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.brainTest.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.brainTest.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.calculator.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.calculator.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.calculator.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.calculator.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.calculator.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.calculator.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.calculator.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.calculator.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.drive.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.drive.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.drive.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.drive.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.drive.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.drive.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.drive.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.drive.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.flashlight.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.flashlight.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.flashlight.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.flashlight.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.flashlight.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.flashlight.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.flashlight.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.flashlight.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.notepad.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.notepad.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.notepad.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.notepad.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.notepad.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.notepad.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.notepad.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.notepad.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.weather.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.weather.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(MiniPrograms.weather.appId),
      publisherApiPolicy: publisherApiPolicyForMiniProgram(MiniPrograms.weather.appId),
      locationPolicy: locationPolicyForMiniProgram(MiniPrograms.weather.appId),
      filePolicy: filePolicyForMiniProgram(MiniPrograms.weather.appId),
      cameraPolicy: cameraPolicyForMiniProgram(MiniPrograms.weather.appId),
      flashlightPolicy: flashlightPolicyForMiniProgram(MiniPrograms.weather.appId),
      requestTimeout: const Duration(seconds: 20),
    ),
  };
}
