// Generated by miniprogram tooling.
// Keep mini-program appId/title pairs in one place when a host app opens
// multiple mini-programs.

class MiniProgramInfo {
  const MiniProgramInfo({
    required this.appId,
    required this.title,
  });

  final String appId;
  final String title;
}
class MiniPrograms {
  const MiniPrograms._();

  static const calculator = MiniProgramInfo(
    appId: "calculator",
    title: "Calculator",
  );

  static const values = <MiniProgramInfo>[
    calculator,
  ];

  static const byAppId = <String, MiniProgramInfo>{
    "calculator": calculator,
  };
}
