// Generated by `miniprogram host endpoint add`.
// Keep endpoint ownership in host config, not button code.
// BEGIN MINI_PROGRAM_ENDPOINTS_JSON
// {"brain_test":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store","backendMode":"none"},"calculator":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store","backendMode":"none"},"weather":{"apiBaseUri":"https://mehedi8603651.github.io/mini-app-store","backendBaseUri":"https://5ibchf95dc.execute-api.ap-south-1.amazonaws.com","backendMode":"remote"}}
// END MINI_PROGRAM_ENDPOINTS_JSON

import 'package:mini_program_sdk/mini_program_sdk.dart';

import 'mini_program_policy_resolver.dart';
import 'mini_program_registry.dart';

Map<String, MiniProgramEndpoint> buildMiniProgramEndpoints() {
  return <String, MiniProgramEndpoint>{
    MiniPrograms.brainTest.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.brainTest.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.brainTest.appId,
      ),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.calculator.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.calculator.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.calculator.appId,
      ),
      requestTimeout: const Duration(seconds: 20),
    ),
    MiniPrograms.weather.appId: MiniProgramEndpoint.public(
      apiBaseUri: Uri.parse("https://mehedi8603651.github.io/mini-app-store"),
      cachePolicy: cachePolicyForMiniProgram(MiniPrograms.weather.appId),
      liveStatePolicy: liveStatePolicyForMiniProgram(
        MiniPrograms.weather.appId,
      ),
      requestTimeout: const Duration(seconds: 20),
      backend: MiniProgramBackendEndpoint(
        baseUri: Uri.parse(
          "https://5ibchf95dc.execute-api.ap-south-1.amazonaws.com",
        ),
        requestTimeout: const Duration(seconds: 30),
      ),
    ),
  };
}
