// Generated by miniprogram tooling.
// Runtime uses accepted host policy only.

import 'package:mini_program_contracts/mini_program_contracts.dart' show MiniProgramLocationAccuracy, MiniProgramLocationMode;
import 'package:mini_program_sdk/mini_program_sdk.dart';

MiniProgramCachePolicy cachePolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramCachePolicy(maxBytes: 262144, maxStateBytes: 262144, stateInactiveTtl: Duration(days: 90), allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{MiniProgramCacheBucket.state});
    case "calculator":
      return const MiniProgramCachePolicy(maxBytes: 1048576, maxStateBytes: 1048576, stateInactiveTtl: Duration(days: 30), allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{MiniProgramCacheBucket.state});
    case "drive":
      return const MiniProgramCachePolicy();
    case "flashlight":
      return const MiniProgramCachePolicy();
    case "notepad":
      return const MiniProgramCachePolicy(maxBytes: 1048576, maxStateBytes: 1048576, stateInactiveTtl: Duration(days: 365), allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{MiniProgramCacheBucket.state});
    case "weather":
      return const MiniProgramCachePolicy(maxBytes: 4325376, maxDataBytes: 4194304, dataTtl: Duration(days: 30), maxStateBytes: 131072, stateInactiveTtl: Duration(days: 90), allowedMiniProgramCacheBuckets: <MiniProgramCacheBucket>{MiniProgramCacheBucket.data, MiniProgramCacheBucket.state});
    default:
      return const MiniProgramCachePolicy();
  }
}

MiniProgramLiveStatePolicy liveStatePolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    case "calculator":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    case "drive":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    case "flashlight":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    case "notepad":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    case "weather":
      return const MiniProgramLiveStatePolicy(maxBytes: 2097152, maxEntries: 1000, maxValueBytes: 262144, maxDepth: 32);
    default:
      return const MiniProgramLiveStatePolicy();
  }
}

MiniProgramPublisherApiPolicy publisherApiPolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "calculator":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "drive":
      return const MiniProgramPublisherApiPolicy(enabled: true);
    case "flashlight":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "notepad":
      return const MiniProgramPublisherApiPolicy(enabled: false);
    case "weather":
      return const MiniProgramPublisherApiPolicy(enabled: true);
    default:
      return const MiniProgramPublisherApiPolicy();
  }
}

MiniProgramLocationPolicy locationPolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramLocationPolicy(enabled: false, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    case "calculator":
      return const MiniProgramLocationPolicy(enabled: false, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    case "drive":
      return const MiniProgramLocationPolicy(enabled: false, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    case "flashlight":
      return const MiniProgramLocationPolicy(enabled: false, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    case "notepad":
      return const MiniProgramLocationPolicy(enabled: false, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    case "weather":
      return const MiniProgramLocationPolicy(enabled: true, accuracy: MiniProgramLocationAccuracy.approximate, mode: MiniProgramLocationMode.whenInUse);
    default:
      return const MiniProgramLocationPolicy();
  }
}

MiniProgramFilePolicy filePolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramFilePolicy();
    case "calculator":
      return const MiniProgramFilePolicy();
    case "drive":
      return const MiniProgramFilePolicy(enabled: true, allowUpload: true, allowDownload: true, allowedMimeTypes: <String>{"*/*"}, allowedDestinations: <MiniProgramFileDownloadDestination>{MiniProgramFileDownloadDestination.downloads, MiniProgramFileDownloadDestination.choose}, maxFilesPerUpload: 3, maxConcurrentTransfers: 2, maxFileBytes: 3145728, minimumFreeBytes: 268435456);
    case "flashlight":
      return const MiniProgramFilePolicy();
    case "notepad":
      return const MiniProgramFilePolicy();
    case "weather":
      return const MiniProgramFilePolicy();
    default:
      return const MiniProgramFilePolicy();
  }
}

MiniProgramCameraPolicy cameraPolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramCameraPolicy(enabled: false, allowPhotoCapture: false);
    case "calculator":
      return const MiniProgramCameraPolicy(enabled: false, allowPhotoCapture: false);
    case "drive":
      return const MiniProgramCameraPolicy(enabled: true, allowPhotoCapture: true);
    case "flashlight":
      return const MiniProgramCameraPolicy(enabled: false, allowPhotoCapture: false);
    case "notepad":
      return const MiniProgramCameraPolicy(enabled: false, allowPhotoCapture: false);
    case "weather":
      return const MiniProgramCameraPolicy(enabled: false, allowPhotoCapture: false);
    default:
      return const MiniProgramCameraPolicy();
  }
}

MiniProgramFlashlightPolicy flashlightPolicyForMiniProgram(
  String appId,
) {
  switch (appId) {
    case "brain_test":
      return const MiniProgramFlashlightPolicy(enabled: false);
    case "calculator":
      return const MiniProgramFlashlightPolicy(enabled: false);
    case "drive":
      return const MiniProgramFlashlightPolicy(enabled: false);
    case "flashlight":
      return const MiniProgramFlashlightPolicy(enabled: true);
    case "notepad":
      return const MiniProgramFlashlightPolicy(enabled: false);
    case "weather":
      return const MiniProgramFlashlightPolicy(enabled: false);
    default:
      return const MiniProgramFlashlightPolicy();
  }
}
