// Generated by mini_program_tooling. Do not edit.
// capabilities: media-playback, qr
dependencies {
    add("implementation", "androidx.media3:media3-exoplayer:1.5.1")
    add("implementation", "androidx.media3:media3-exoplayer-hls:1.5.1")
    add("implementation", "androidx.media3:media3-ui:1.5.1")
    add("implementation", "androidx.media3:media3-datasource:1.5.1")
    add("implementation", "androidx.media3:media3-database:1.5.1")
    add("implementation", "androidx.camera:camera-camera2:1.4.2")
    add("implementation", "androidx.camera:camera-lifecycle:1.4.2")
    add("implementation", "androidx.camera:camera-view:1.4.2")
    add("implementation", "com.google.mlkit:barcode-scanning:17.3.0")
}
